feat(alert): #MA-968 init data to set up excluded alerts rules
OPEN-ENT-NG/presences pull request #137
Opened 2022-06-23 09:02 UTC by BastienBenard

## Describe your changes
Party 1/3 of the ticket [MA-662](https://entsupport.gdapublic.fr/browse/MA-662)

Edit table for the MA-662.
MA-662 makes alerts configurable.

The tests are provided in the PR #140 

Doc: https://entconf.gdapublic.fr/pages/viewpage.action?pageId=96436457

The files in the "SQLReverseScript" folder is used in case of a problem in production. They must allow to restore the database to the state before the ticket. They will be deleted in the PR of the MA-770 ticket.

## Checklist tests
Nothing. Just execute this file after MA-662 complete 
https://github.com/OPEN-ENT-NG/presences/pull/140/files#diff-849bfe6ffcfd3d258ea47768804e674f38c73d03c0da7520bebbcbef54fbccd2

## Issue ticket number and link
[MA-968](https://entsupport.gdapublic.fr/browse/MA-968)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-28 14:17 UTC, flmartineau approved these changes

2022-06-28 14:32 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +    CONSTRAINT check_types CHECK (rule_value IN ('REGULARIZED', 'UNREGULARIZED', 'LATENESS'))
D'après la doc, pourquoi le choix du nom "rule_value" ? Elle représente une valeur dans laquelle on veut exclure un motif de ces types là ?
Comment est-ce que tu comptes l'utiliser cette info ?

2022-06-29 08:39 UTC, BastienBenard commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +    CONSTRAINT check_types CHECK (rule_value IN ('REGULARIZED', 'UNREGULARIZED', 'LATENESS'))
J'ai rajouté cette parti dans la doc
![image](https://user-images.githubusercontent.com/95362455/176391449-d29c4baf-bb60-44f0-87c6-78045b7de9a8.png)

Ensuite dans les triggers on va pouvoir voir si les evenements doivent etre exclue ou pas en rechercher l'id de la raison dans la table presences.reason_alert_rules.

Exemple pour un évènement de type retard avec le motif id1:
- si on a un ligne (structure_motif, id_motif, LATENESS) alors l'évènement est exclue des alerts

2022-06-29 12:11 UTC, qpic-cgi commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +            INSERT INTO presences.reason_alert(structure_id, reason_id, reason_alert_exclude_rules_type_id) VALUES (reason.structure_id, reason.id, 1);
Attention a l'avenir, le "rule_type" type est unique et plus parlant (il fait un peu office de slug).
Il sera préférable de manipuler les "reason_alert_exclude_rules_type" avec ce "rule_type"

2022-06-29 12:12 UTC, qpic-cgi commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +    delete_at timestamp without time zone,
dommage d'avoir un "create_date" et un "delete_at". Ce serait cool de choisir qu'un seul format parmi ces 2 options

2022-06-29 12:14 UTC, qpic-cgi commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +);
n'est-il pas plus intéressant de faire de cette donné une constante plutôt qu'une table SQL ?

2022-06-29 12:42 UTC, BastienBenard commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +            INSERT INTO presences.reason_alert(structure_id, reason_id, reason_alert_exclude_rules_type_id) VALUES (reason.structure_id, reason.id, 1);
Vu avec @JinDouang, mettre un id permettra de rendre la table flexible au future évolution.

2022-06-29 12:44 UTC, qpic-cgi approved these changes

2022-06-29 13:38 UTC, JinDouang requested changes

2022-06-29 13:38 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +ALTER TABLE incidents.seriousness ADD COLUMN exclude_alert_seriousness boolean NOT NULL DEFAULT FALSE;
A faire dans son module plutôt

2022-06-29 13:38 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +                               ADD COLUMN exclude_alert_forgotten_notebook boolean NOT NULL DEFAULT FALSE;
Pour que le trigger puisse les utiliser, c'est bien ça ?

2022-06-29 13:38 UTC, JinDouang commented on incidents/src/main/resources/sql/020-MA-968-make-alerts-configurable-reverse.sql
> +ALTER TABLE incidents.seriousness ADD COLUMN exclude_alert_seriousness boolean NOT NULL DEFAULT FALSE;
pourquoi reverse ?

2022-06-29 13:38 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +    create_at timestamp without time zone NOT NULL DEFAULT now(),
created_at et deleted_at

2022-06-29 13:43 UTC, BastienBenard commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +                               ADD COLUMN exclude_alert_forgotten_notebook boolean NOT NULL DEFAULT FALSE;
Oui

2022-06-29 13:52 UTC, JinDouang commented on incidents/src/main/resources/sql/020-MA-968-make-alerts-configurable.sql
> +ALTER TABLE incidents.seriousness ADD COLUMN exclude_alert_seriousness boolean NOT NULL DEFAULT FALSE;
Permet de conditionner l'exclusion (si on le prend en compte dans les alertes pour l'incident en question) pour seriousness

2022-06-29 13:55 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +ALTER TABLE presences.settings ADD COLUMN exclude_alert_absence_no_reason boolean NOT NULL DEFAULT FALSE,
Same patterns applied for absence event's type without reason, lateness event's without reason and forgotten notebook

Note: We can add more type of rule of these case in the future

2022-06-29 13:57 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +CREATE TABLE presences.reason_alert_exclude_rules_type(
Since we have :

- REGULARIZED
- UNREGULARIZED
- LATENESS

We create a table with exclude rule type to apply for our relational `reason_alert` (see below)

2022-06-29 13:59 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +CREATE TABLE presences.reason_alert
This will be used while creating a new reason (or update), it will insert a new line of reason_alert with the excluding rule 

TRIGGERS will be able to use this table in order to check whether they should count alert of this matter or not

2022-06-29 14:00 UTC, JinDouang commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +    deleted_at timestamp without time zone,
Only if we decided to not use this alert rule anymore

Note : it will be definitely removed only if the reason is deleted (trigger shall be implemented)

2022-06-29 14:02 UTC, JinDouang approved these changes

2022-06-29 14:11 UTC, merged