feat(alert): #MA-965 edit trigger for count alert by line
OPEN-ENT-NG/presences pull request #138
Opened 2022-06-23 09:02 UTC by BastienBenard

## Describe your changes
Party 2/3 of the ticket [MA-770](https://entsupport.gdapublic.fr/browse/MA-770)

Edit trigger and function for the MA-770.
MA-770 aims to make alerts resettable by dates.

The tests are provided in the PR #140 

Doc: https://entconf.gdapublic.fr/pages/viewpage.action?pageId=96436457

The files in the "SQLReverseScript" folder is used in case of a problem in production. They must allow to restore the database to the state before the ticket. They will be deleted in the PR of the MA-770 ticket.

## Checklist tests
Nothing. Just execute this file after MA-662 complete 
https://github.com/OPEN-ENT-NG/presences/pull/140/files#diff-849bfe6ffcfd3d258ea47768804e674f38c73d03c0da7520bebbcbef54fbccd2

## Issue ticket number and link
[MA-965](https://entsupport.gdapublic.fr/browse/MA-965)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-28 08:53 UTC, BastienBenard commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +DROP FUNCTION presences.exists_absence_in_day(date, character varying, character varying);
Les triggers qui utilisent ces fonction seront modifié dans la MA-966

2022-06-28 13:19 UTC, JinDouang approved these changes

2022-06-28 14:31 UTC, JinDouang requested changes

2022-06-28 14:31 UTC, JinDouang commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +-- Return id of the event included in the provided date. The event in parma is exclude.
parma ?

2022-06-28 14:31 UTC, JinDouang commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +-- Return id of the event included in the provided date. The event in parma is exclude.
parma ?

2022-06-28 14:31 UTC, JinDouang commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +CREATE FUNCTION presences.get_id_other_absence_in_same_date(event presences.event, structureIdentifier varchar, needAlert boolean) RETURNS bigint AS
Je pense tu peux trouver un autre nom de fonction

d'autant plus que tu ne récupères pas vraiment de date dans ton param donc c'est "faussé"

2022-06-28 14:31 UTC, JinDouang commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +CREATE FUNCTION presences.get_id_other_absence_in_same_date(absenceEvent presences.event, startTime time, endTime time, needAlert boolean) RETURNS bigint AS
Tu peux décrire le "other_absence" ?

2022-06-28 14:31 UTC, JinDouang commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +CREATE FUNCTION presences.get_id_other_absence_in_same_date(event presences.event, structureIdentifier varchar, needAlert boolean) RETURNS bigint AS
structureId plutôt non ?

2022-06-28 14:31 UTC, JinDouang commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +-- Return id of the event included in the provided date. The event in parma is exclude.
d'ailleurs c la même description par rapport à l'autre fonction

2022-06-28 14:32 UTC, flmartineau commented on presences/src/main/resources/sql/045-MA-965-edit-trigger-count-by-line.sql
> +CREATE FUNCTION presences.get_id_other_absence_in_same_date(event presences.event, structureIdentifier varchar, needAlert boolean) RETURNS bigint AS
Essaye de d'expliquer en commentaire les paramètres de ta fonction

2022-06-29 07:47 UTC, flmartineau approved these changes

2022-06-29 09:18 UTC, JinDouang approved these changes

2022-06-29 09:19 UTC, merged