feat(incidents): #MA-949 add class/groups searchbar on incidents list
OPEN-ENT-NG/presences pull request #141
Opened 2022-06-28 14:07 UTC by flmartineau

## Describe your changes

- Add a class/groups search bar for the incidents list

## Checklist tests

- check if searching classes is working properly
- -check if searching students is still behaving normally

## Issue ticket number and link

https://entsupport.gdapublic.fr/browse/MA-949

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-28 15:07 UTC, JinDouang requested changes

2022-06-28 15:07 UTC, JinDouang commented on incidents/src/main/java/fr/openent/incidents/controller/IncidentsController.java
> +        this.groupService = new DefaultGroupService(eb);
CommonService!

2022-06-28 15:07 UTC, JinDouang commented on incidents/src/main/java/fr/openent/incidents/controller/IncidentsController.java
> +                            .map((JsonObject s) -> s.getString(Field.ID)).collect(Collectors.toList());
Si jamais tu obtiens [id, id, null] tu risques d'avoir un problème
Il faudrait le gérer :  

`studentIds .removeAll(Collections.singletonList(null))`;

2022-06-28 15:07 UTC, JinDouang commented on incidents/src/main/java/fr/openent/incidents/controller/IncidentsController.java
> +                    List<String> studentIds = ((List<JsonObject>) groupStudents.getList()).stream()
Si jamais tu obtiens [id, id, null] tu risques d'avoir un problème
Il faudrait le gérer :

`studentIds .removeAll(Collections.singletonList(null));`

2022-06-28 15:59 UTC, BastienBenard commented on incidents/src/main/resources/public/ts/controllers/incidents.ts
> +                vm.filter.groups = vm.groupsSearch.getSelectedGroups().map(group => group["id"]);
Est ce que c'est possible d'essayer de typer getSelectedGroups() ?

2022-06-28 16:01 UTC, BastienBenard reviewed
Il me semble que tu n'es pas a jour avec dev

2022-06-28 16:08 UTC, JinDouang requested changes

2022-06-28 16:08 UTC, JinDouang commented on incidents/src/main/java/fr/openent/incidents/Incidents.java
> +        CommonServiceFactory commonServiceFactory = new CommonServiceFactory(vertx);
commonIncidentService du coup!

2022-06-29 08:02 UTC, flmartineau commented on incidents/src/main/resources/public/ts/controllers/incidents.ts
> +                vm.filter.groups = vm.groupsSearch.getSelectedGroups().map(group => group["id"]);
Ca implique de typer tout le fichier groupSearch et potentiellement de gérer les problèmes de typages partout où il est utilisé

2022-06-29 09:20 UTC, JinDouang approved these changes

2022-06-29 09:21 UTC, BastienBenard approved these changes

2022-06-29 09:26 UTC, merged

2022-06-29 09:34 UTC, aymericdevriesere commented on incidents/src/main/java/fr/openent/incidents/service/CommonIncidentsServiceFactory.java
> +    public CommonIncidentsServiceFactory(Vertx vertx) {
Pourquoi créer un classe dont le seul but vas être d'instancier une autre ?