feat(alert): #MA-963 add parameter for configurable alerts in viesco
OPEN-ENT-NG/presences pull request #146
Opened 2022-07-07 12:27 UTC by BastienBenard

## Describe your changes
Parti 3/3 de la [MA-662](https://entsupport.gdapublic.fr/browse/MA-662)
Front et back de la  MA-662.
MA-662 permet de rendre les alertes configurables.

API: https://confluence.support-ent.fr/pages/viewpage.action?pageId=36707774
https://confluence.support-ent.fr/display/MP/Settings+API
https://confluence.support-ent.fr/pages/viewpage.action?pageId=36708291

Doc MA-662: https://entconf.gdapublic.fr/pages/viewpage.action?pageId=96436457

Mise a jour dépendance:
es2015 -> es2017

## Checklist tests
Créer des raisons d'absence en excluant les sans motif, les régularisées et les non régularisées.
Créer des raisons de retard en excluant les sans motif.
Exclure des niveaux d'alerte

## Issue ticket number and link
[MA-963](https://entsupport.gdapublic.fr/browse/MA-963)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to this project (must specify in **Description**)

2022-07-07 14:23 UTC, BastienBenard commented on common/src/main/java/fr/openent/presences/common/helper/FutureHelper.java
> +
utilisation d'un méthode avec des raw parametre. Ce qui rend déprécié  handlerJsonArray et handlerJsonObject

2022-07-07 14:25 UTC, BastienBenard commented on common/src/main/java/fr/openent/presences/enums/SettingsFieldEnum.java
> +    EXCLUDE_ALERT_FORGOTTEN_NOTEBOOK("exclude_alert_forgotten_notebook"),
Rajout des nouveaux champs de la table

2022-07-07 14:26 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/controller/SeriousnessController.java
> +        RequestUtils.bodyToJson(request, pathPrefix + "seriousnessCreate", seriousnessBody -> {
Ici on rajout un json schémas pour vérifier les paramètre de la requete

2022-07-07 14:26 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/controller/SeriousnessController.java
> +                    });
Utilisation de future plutot que les handlers

2022-07-07 14:27 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/controller/SeriousnessController.java
> +        RequestUtils.bodyToJson(request, pathPrefix + "seriousnessUpdate", seriousnessBody -> {
Ici on rajout un json schémas pour vérifier les paramètre de la requete

2022-07-07 14:27 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/controller/SeriousnessController.java
> +                    });
Utilisation de future plutot que les handlers

2022-07-07 14:27 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/service/SeriousnessService.java
> +    Future<JsonObject> create(JsonObject seriousnessBody);
Utilisation de future plutot que les handlers

2022-07-07 14:27 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/service/SeriousnessService.java
> +    Future<JsonObject> put(JsonObject seriousnessBody);
Utilisation de future plutot que les handlers

2022-07-07 14:28 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/service/impl/DefaultSeriousnessService.java
> +                "(structure_id, label, level, hidden, exclude_alert_seriousness)" +
Rajout du champ pour exclure un niveaux de gravité des alertes

2022-07-07 14:28 UTC, BastienBenard commented on incidents/src/main/java/fr/openent/incidents/service/impl/DefaultSeriousnessService.java
> +                "SET label = ?, level = ?, hidden = ?, exclude_alert_seriousness = ?  WHERE id = ? RETURNING id";
Rajout du champ pour exclure un niveaux de gravité des alertes

2022-07-07 14:33 UTC, BastienBenard commented on incidents/src/main/resources/public/sass/global/components/incidents/_sniplets.scss
> +      }
Ce css permet d'inverse la checkBox.
Exemple
- [ x] Ce motif compte dans les alertes -> excludeAlerte (ce motif est exclue ?) = false

2022-07-07 14:41 UTC, BastienBenard commented on incidents/src/main/resources/public/template/behaviours/sniplet-incidents-manage/sniplet-incidents-manage-lightbox.html
> +
![image](https://user-images.githubusercontent.com/95362455/177800998-c8cfe042-5b8d-4658-84fb-496bb2629ef5.png)
Ne pas faire attention au i18 ils ne seront pas valide au moment de mon screen

2022-07-07 14:46 UTC, BastienBenard commented on incidents/src/main/resources/public/template/behaviours/sniplet-incidents-manage/sniplet-incidents-seriousness-manage.html
> +
![image](https://user-images.githubusercontent.com/95362455/177800998-c8cfe042-5b8d-4658-84fb-496bb2629ef5.png)
Ne pas faire attention au i18, voir https://github.com/OPEN-ENT-NG/presences/pull/147 et https://github.com/OPEN-ENT-NG/vie-scolaire/pull/33

2022-07-07 14:49 UTC, BastienBenard commented on incidents/src/main/resources/public/template/behaviours/sniplet-incidents-manage/sniplet-incidents-seriousness-manage.html
> +                               ng-style="{ 'color': vm.getSeriousnessAlertColor(seriousness)}"></i>
![image](https://user-images.githubusercontent.com/95362455/177803205-90d4f1b4-e9e8-427e-8808-2533b29b58a0.png)

2022-07-07 14:50 UTC, BastienBenard commented on incidents/src/main/resources/public/ts/sniplets/incidents-manage/incidentsSeriousnessManage.ts
> -}
Plus utiliser. On utilise la méthode static de common

2022-07-07 14:51 UTC, BastienBenard commented on incidents/src/main/resources/public/ts/sniplets/incidents-manage/incidentsSeriousnessManage.ts
> +export class IncidentsSeriousnessManage implements ViewModel {
Utilisation de classe plutot que VModel

2022-07-07 14:57 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/ReasonController.java
> +                .onFailure(error -> renderError(request));
Utilisation de future a la place des handlers

2022-07-07 14:58 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/ReasonController.java
> +                    });
Utilisation de future a la place des handlers

2022-07-08 07:03 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/ReasonController.java
> +        RequestUtils.bodyToJson(request,pathPrefix + "reasonUpdate", reasonBody -> {
Ici on rajout un json schémas pour vérifier les paramètre de la requete

2022-07-08 07:04 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/ReasonController.java
> +                    });
Utilisation de future a la place des handlers

2022-07-08 07:04 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/SettingsController.java
> +        );
Utilisation de future a la place des handlers

2022-07-08 07:05 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/ReasonService.java
> +    Future<JsonArray> get(String structureId, Integer reasonTypeId);
Utilisation de future a la place des handlers

2022-07-08 07:05 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/ReasonService.java
> +    Future<JsonObject> create(JsonObject reasonBody);
Utilisation de future a la place des handlers

2022-07-08 07:05 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/ReasonService.java
> +    Future<JsonObject> put(JsonObject reasonBody);
Utilisation de future a la place des handlers

2022-07-08 07:05 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/SettingsService.java
> +    Future<JsonObject> put(String structureId, JsonObject settings);
Utilisation de future a la place des handlers

2022-07-08 07:06 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultReasonService.java
> +    public Future<JsonArray> get(String structureId, Integer reasonTypeId) {
Utilisation de future a la place des handlers

2022-07-08 07:07 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultReasonService.java
> -        CompositeFuture.all(reasonsFuture, reasonsUsedFuture).setHandler(event -> {
setHandler est déprécier

2022-07-08 08:40 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultReasonService.java
> +                            });
On crée la raison pour on crée les règle exclusion associer a cette raison

2022-07-08 08:45 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultReasonService.java
> +            query = "INSERT INTO " + Presences.dbSchema + ".reason_alert(structure_id, reason_id, reason_alert_exclude_rules_type_id) VALUES (?, ?, " + reasonAlertExcludeRulesType.getValue() + ") ON
Si on échou l'insertion sur la containte uniq_reason_alert, c'est que la régle d'exclusion a déjà etais "supprimé" (mise a non null du champ deleted_at). Dans ce cas on ne recrée pas la ligne, on met juste deleted_at a Null pour "réactiver" la règle

2022-07-08 08:50 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultReasonService.java
> +            query = "UPDATE " + Presences.dbSchema + ".reason_alert SET deleted_at = now() WHERE structure_id = ? AND reason_id = ? AND reason_alert_exclude_rules_type_id = " + reasonAlertExcludeRule
On ne supprime jamais réelement une règle. On met a non null le champ deleted_at pour "désactivé" la règle.

2022-07-08 08:53 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultSettingsService.java
> +                "exclude_alert_forgotten_notebook " +
rajout des nouveaux champs de la table settings

2022-07-08 08:54 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultSettingsService.java
> +                update(structureId, settings, promise.future());
Utilisation des future

2022-07-08 09:03 UTC, BastienBenard commented on presences/src/main/resources/public/sass/global/components/sniplets/_presences-manage-absence.scss
> +
Ce css permet d'inverse la checkBox.
Exemple

- [ ] Ce motif compte dans les alertes -> excludeAlerte (ce motif est exclue ?) = false

2022-07-08 09:04 UTC, BastienBenard commented on presences/src/main/resources/public/sass/global/components/sniplets/_presences-manage-absence.scss
> +      }
Ce css permet d'inverse la checkBox.
Exemple

- [x] Ce motif compte dans les alertes -> excludeAlerte (ce motif est exclue ?) = false

2022-07-08 09:06 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/alert-manage/sniplet-presences-alert-manage.html
> +        </div>
![image](https://user-images.githubusercontent.com/95362455/177958180-44501588-38eb-4aae-a0aa-606e4a18c64e.png)

2022-07-08 09:07 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/reason-manage/sniplet-presences-reason-manage-absence.html
> +        </div>
![image](https://user-images.githubusercontent.com/95362455/177958373-65ef9d67-129c-437b-a285-68edeb5a31fb.png)

2022-07-08 09:08 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/reason-manage/sniplet-presences-reason-manage-absence.html
> +                               ng-style="{ 'color': vm.getReasonAlertColor(reason)}"></i>
![image](https://user-images.githubusercontent.com/95362455/177958548-b565211f-6ba2-4e67-9d60-5ef1c14993d5.png)

2022-07-08 09:09 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/reason-manage/sniplet-presences-reason-manage-lateness.html
> +
![image](https://user-images.githubusercontent.com/95362455/177958698-aef58b6d-ebd1-4a0a-8364-cbe6363bf11c.png)

2022-07-08 09:09 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/reason-manage/sniplet-presences-reason-manage-lateness.html
> +                               ng-style="{ 'color': vm.getReasonAlertColor(reason)}"></i>
![image](https://user-images.githubusercontent.com/95362455/177958803-0d72b329-32af-43f9-a0c9-d4e66f1225fa.png)

2022-07-08 09:12 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/reason-manage/sniplet-presences-reason-manage-lightbox.html
> +            </div>
![image](https://user-images.githubusercontent.com/95362455/177959188-5d56b327-20c4-406a-88fa-90d627ea2973.png)

2022-07-08 11:51 UTC, BastienBenard commented on presences/src/main/resources/public/template/behaviours/sniplet-presences-manage/reason-manage/sniplet-presences-reason-manage-lightbox.html
> +        </div>
![image](https://user-images.githubusercontent.com/95362455/177986898-5f9ffece-b928-4b00-993e-bf50b51e91b2.png)

2022-07-08 11:53 UTC, BastienBenard commented on presences/src/main/resources/public/ts/sniplets/presences-manage/presences-alert-manage.ts
> +class AlertManage implements IViewModel {
Utilisation de class plutôt que VModel

2022-07-08 12:03 UTC, BastienBenard commented on presences/src/main/resources/sql/046-MA-968-make-alerts-configurable.sql
> +    reason_alert_exclude_rules_type_id bigserial REFERENCES presences.reason_alert_exclude_rules_type(id) NOT NULL,
Ajout de contrainte non null. On peut modifier directement l'ancien fichier car tout sera directement merge dans MA-662

2022-07-08 12:31 UTC, BastienBenard commented on tsconfig.json
> +      "es2017",
Mise a jour de la lib, permet de faire des includes sur des Arrays

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.alert.rules": "This reason counts in the alerts",
is part of the alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.alert.rules.no.regularised": "When it is unregulated",
unregularized

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.absence.reason.regularized.and.unregularized": "Alert when the absence is regularized or not regularized",
alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.absence.reason.regularized": "Alert when this reason is regularized",
alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.absence.reason.unregularized": "Alert when this reason is not regularized",
alerts + unregularized

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.absence.reason.lateness": "Alert for this reason",
alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.alerts.exclude.absence.no.reason": "Absences without reason count in alerts",
are part of the alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.alerts.exclude.lateness.no.reason": "Lateness without reason count in alerts",
are part of the alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/en.json
> +  "presences.alerts.exclude.foregotten.notebook": "Forgotten notebooks count in alerts"
are part of the alerts

2022-07-08 14:48 UTC, alicedraillard commented on presences/src/main/resources/i18n/fr.json
> +  "presences.absence.reason.regularized.and.unregularized": "Alerte lorsque l'absence est régularisé ou non régularisé",
régularisée

2022-07-08 14:48 UTC, alicedraillard commented on incidents/src/main/resources/i18n/en.json
> +  "incidents.names": "Names",
en and fr i18n do not have the same fields

2022-07-08 14:48 UTC, alicedraillard commented on incidents/src/main/resources/i18n/en.json
> +  "incidents.seriousness.alert": "Alert for this severity level"
alerts

2022-07-18 09:14 UTC, JinDouang requested changes

2022-07-18 09:14 UTC, JinDouang commented on tsconfig.json
> +      "es2017",
Pour cette fois-ci on ne l'implémentera pas car :
- C'est une décision qu'on doit voir avec ODE (dans le cas où on voudrait être en ES2017, il faudra l'adapter sur tous les modules)
- on peut utiliser les includes (c'est juste que dans cette version on ne doit pas préciser le typage si on veut pouvoir l'utiliser)

2022-07-18 09:14 UTC, JinDouang commented on presences/src/main/resources/public/ts/models/Reason.ts
> +    reason_alert_rules: Array<ALERT_RULE>;
Dommage de le rendre obligatoire car ça te force à maj tes tests/controllers..
Tu peux pas le rendre optionnel ?

2022-07-18 09:14 UTC, JinDouang commented on presences/src/main/resources/public/ts/models/Reason.ts
> +    excludeAlertRegularised: boolean;
idem, possibilité de le rendre optionnel ?
Car après tu es amené à tout maj..

2022-07-18 12:13 UTC, BastienBenard commented on presences/src/main/resources/public/ts/models/Reason.ts
> +    excludeAlertRegularised: boolean;
Dans ce cas la, comme le model représente l'appel d'API, il est obligatoire d'avoir ces champs. Voir la doc

2022-07-18 15:43 UTC, JinDouang approved these changes

2022-07-18 15:45 UTC, merged