feat(search): #193 add api uses event bus to search grouping
OPEN-ENT-NG/presences pull request #194
Opened 2022-09-12 12:46 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-12 13:09 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/AlertController.java
> +    @ResourceFilter(UserInStructure.class)
Renommage pour réutilisation.

2022-09-12 13:09 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/controller/AlertController.java
> +import fr.openent.presences.security.UserInStructure;
Renommage pour réutilisation.

2022-09-12 13:09 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/security/UserInStructure.java
> +public class UserInStructure implements ResourcesProvider {
Renommage pour réutilisation.

2022-09-16 10:12 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/Presences.java
> +        addController(new GroupingController());
Utilise factory Service

2022-09-16 10:21 UTC, JinDouang requested changes

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/controller/GroupingController.java
> +        groupingService = new DefaultGroupingService();
Utilise le factory service

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +public class Grouping {
Tu pourrais faire ça dans le "common" (si jamais les autres modules veulent l'utiliser) et même utiliser ça : 

https://github.com/CGI-OPEN-ENT-NG/minibadge/blob/dev/src/main/java/fr/cgi/minibadge/model/Model.java

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    public static Grouping fromJson(JsonObject grouping) {
C'est une méthode très fonctionnel j'ai l'impression non ?

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    }
Mets les en bas, tes getter/setter doivent être en haut

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    public Grouping setStudent_divisions(List<StudentDivision> student_divisions) {
camelCase

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    public Grouping setStructure_id(String structure_id) {
camelCase

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    public List<StudentDivision> getStudent_divisions() {
camelCase

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    public String getStructure_id() {
camelCase

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +        this.student_divisions = student_divisions;
camelCase

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/Grouping.java
> +    private List<StudentDivision> student_divisions;
camelCase

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/StudentDivision.java
> +public class StudentDivision {
Ca pourrait être dans le common

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/model/grouping/StudentDivision.java
> +    }
Les getter/setter avant

2022-09-16 10:21 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultGroupingService.java
> +                .map(Grouping::fromJson)
finalement, passer par un constructeur ça pourrait le faire non ?

2022-09-19 08:26 UTC, BastienBenard commented on common/src/main/java/fr/openent/presences/common/helper/IModelHelper.java
> +package fr.openent.presences.common.helper;
Ce fichier de test permet de vérifier la bon implémentation des classe implémentant IModel dans Common.

2022-09-19 08:29 UTC, BastienBenard commented on common/src/test/java/fr/openent/presences/common/helper/IModelHelperTest.java
> +package fr.openent.presences.common.helper;
193-add-api-grouping

2022-09-19 08:30 UTC, BastienBenard commented on incidents/src/test/java/fr/openent/incidents/helper/IModelHelperTest.java
> +package fr.openent.incidents.helper;
Ce fichier permet de vérifier l'implementation des classes implémentant IModel dans Incident

2022-09-19 08:31 UTC, BastienBenard commented on massmailing/src/test/java/fr/openent/massmailing/helper/IModelHelperTest.java
> +package fr.openent.massmailing.helper;
Ce fichier permet de vérifier l'implementation des classes implémentant IModel dans Massmailing

2022-09-20 08:05 UTC, JinDouang approved these changes

2022-09-20 08:06 UTC, merged

2022-09-23 07:21 UTC, BastienBenard commented
J'ai oublié de noter l'ajout de dépendance dans la description de la PR
org.reflections:reflections:0.10.2