fix(permission): #MA-1041 add access to the presences features when restricted rights
OPEN-ENT-NG/presences pull request #258
Opened 2022-11-21 15:44 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-21 16:07 UTC, alicedraillard requested changes

2022-11-21 16:07 UTC, alicedraillard commented on presences/src/main/resources/public/template/behaviours/sniplet-navigation.html
> +                        hasRight('readExemption') || hasRight('readExemptionRestricted') || hasRight('manageCollectiveAbsences')"
C'est possible d'appeler plutôt une fonction qui va retourner le résultat de tte cette logique ?

2022-11-21 16:07 UTC, alicedraillard commented on presences/src/main/resources/public/template/behaviours/sniplet-navigation.html
> +                        hasRight('readExemption') || hasRight('readExemptionRestricted') || hasRight('manageCollectiveAbsences')">
idem

2022-11-22 08:45 UTC, alicedraillard approved these changes

2022-11-22 09:17 UTC, Matiyeu approved these changes

2022-11-22 10:03 UTC, merged