fix(log): #MA-1059 add log when method fail
OPEN-ENT-NG/presences pull request #278
Opened 2022-12-23 09:49 UTC by BastienBenard

## Describe your changes
Add log when method fail

## Issue ticket number and link
[MA-1059](https://jira.support-ent.fr/browse/MA-1059)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-12-23 10:09 UTC, sjollois approved these changes

2022-12-23 11:03 UTC, qpic-cgi requested changes

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
> +                                        this.getClass().getSimpleName(), fail.getMessage()));
Ta méthode "setRestrictedTeacherFilter" gère déjà le failure.

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
> +                                    this.getClass().getSimpleName(), fail.getMessage()));
Ta méthode "setRestrictedTeacherFilter" gère déjà le failure.

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
> +                            this.getClass().getSimpleName(), fail.getMessage()));
Ta méthode "setRestrictedTeacherFilter" gère déjà le failure.

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
>              CompositeFuture.all(restrictedClassesFuture, restrictedStudentFuture)
Problème avec la méthode "getGroupsAndClassesFromTeacherId", elle ne log pas d'erreur !!

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
>              CompositeFuture.all(restrictedClassesFuture, restrictedStudentFuture)
Problème avec la méthode "getStudentsFromTeacher", elle ne log pas d'erreur !!

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
> +                        promise.fail(fail);
si tes 2 méthodes du dessus étaient bien loguées, tu n'aurais pas besoin de logs ici.

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
>              statisticsPresencesService.fetchUsers(structures, startDate).compose(structureStatisticsUserList ->
Ici tu as un workflow particulier: https://github.com/OPEN-ENT-NG/presences/blob/ad89cd6b6093d7831db0e88df14ade4b13ab4521/statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsPresencesService.java#L194
Il n'y a pas de on failure !

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
> +                                this.getClass().getSimpleName(), fail.getMessage()));
Ici tu as un workflow particulier:

[presences/statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsPresencesService.java](https://github.com/OPEN-ENT-NG/presences/blob/ad89cd6b6093d7831db0e88df14ade4b13ab4521/statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsPresencesService.java#L194)

Line 194 in [ad89cd6](https://github.com/OPEN-ENT-NG/presences/commit/ad89cd6b6093d7831db0e88df14ade4b13ab4521)

 schoolDateFuture.onSuccess(schoolDate -> { 

Il n'y a pas de on failure !

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/indicator/IndicatorGeneric.java
> +                            IndicatorGeneric.class.getSimpleName(), error.getMessage()));
"manualStart" est déjà loggué.

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/indicator/ProcessingScheduledManual.java
> +                            this.getClass().getSimpleName(), error.getMessage()));
"fetchAllStudentsFromStructure" est déjà logué correctement.

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsService.java
> +                                this.getClass().getSimpleName(), error.getMessage()));
"deleteOldValuesForStudent" est déjà bien loguée

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsService.java
> +                        promise.fail(error);
la méthode "storeValues" est déjà bien loguée

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsPresencesService.java
> +                            promise.fail(error);
"computeStatistics.start" est déjà bien loguée

2022-12-23 11:03 UTC, qpic-cgi commented on statistics-presences/src/main/java/fr/openent/statistics_presences/service/impl/DefaultStatisticsPresencesService.java
> +                                                this.getClass().getSimpleName(), error.getMessage()));
"computeStatistics.start" est déjà bien loguée

2022-12-23 17:12 UTC, BastienBenard commented on statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java
>              statisticsPresencesService.fetchUsers(structures, startDate).compose(structureStatisticsUserList ->
bien vu

2022-12-29 08:28 UTC, JinDouang approved these changes

2022-12-29 11:27 UTC, merged