fix(security): #MA-1083 fix statistics graph when not from struct or …
OPEN-ENT-NG/presences pull request #300
Opened 2023-04-18 14:24 UTC by Alex-Delaveau

## Describe your changes

Added resource filter to check if user who is trying to get the statistics graph is from the right structures and has the rights to do so.

## Checklist tests

## Issue ticket number and link
[MA-1083](https://jira.support-ent.fr/browse/MA-1083)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-18 15:10 UTC, alicedraillard approved these changes
nom de commit pas assez clair --> idée:
fix statistics graph for wrong structure and right absence

2023-04-18 17:43 UTC, JinDouang requested changes

2023-04-18 17:43 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/security/StatisticsViewRightAndStruct.java
> +        String structure = request.getParam(Field.STRUCTUREID);
l'endpoint en question est "structure" comme le demande l'endpoint, tu n'as pas besoin de faire plusieurs verif de plusieurs param ("structure", structureId" etc...)

2023-04-18 17:43 UTC, JinDouang commented on presences/src/main/java/fr/openent/presences/controller/StatisticsController.java
>      @Post("/statistics/structures/:structure/student/:student/graph")
cf commentaire en-dessous, `:structure`

2023-04-19 12:46 UTC, JinDouang approved these changes

2023-04-19 12:55 UTC, merged