fix(multimailing) : #MA-1096 fix students filter list depleting when selecting a student when one was already selected.
OPEN-ENT-NG/presences pull request #310
Opened 2023-05-03 13:53 UTC by FlorentMr

## Describe your changes
fix students filter list depleting when selecting a student when one was already selected because of emptying too much the selectedStudent tab.

## Checklist tests
Publipostage -> Bouton des filtres (à gauche de Absences sans motif) -> Sélectionner plusieurs élèves via la liste, ils sont sensés s'afficher ensemble.

## Issue ticket number and link
[MA-1096](https://jira.support-ent.fr/browse/MA-1096)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-03 14:07 UTC, Alex-Delaveau approved these changes

2023-05-03 15:08 UTC, JinDouang requested changes

2023-05-03 15:08 UTC, JinDouang commented on common/src/main/resources/ts/utils/autocomplete/studentsSearch.ts
> +        if (this._selectedStudents == null)
Cette classe utile qui est dans le common, est utilisé sur plusieurs controller/composant html/ts

on aura pas de probleme sur les autres usages ?

2023-05-04 08:46 UTC, FlorentMr commented on common/src/main/resources/ts/utils/autocomplete/studentsSearch.ts
> +        if (this._selectedStudents == null)
Après discussion, c'était en effet plutôt une fonction mal utilisée qu'une fonction mal définie, c'est changé

2023-05-04 09:20 UTC, JinDouang approved these changes

2023-05-11 09:06 UTC, merged