feat(infinite-scroll): #MA-988 infinite-scroll for alerts
OPEN-ENT-NG/presences pull request #321
Opened 2023-05-26 10:36 UTC by Alex-Delaveau

## Describe your changes

implement an infinite-scroll for alerts with a lazy loading.

## Checklist tests

In Présences > Evénement > Alertes 

Verify that there are more than 20 alerts available for loading. This is a prerequisite for the lazy loading feature to function as intended.

Scroll down the list of alerts. As you reach the end of the initial list, check for the presence of a loading icon.

Once the loading icon disappears, confirm that a new set of alerts is displayed.

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-26 13:04 UTC, qpic-cgi requested changes
De manière général, fait attention à ton indentation dans tous les fichiers

2023-05-26 13:04 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +        }
```suggestion
        if(page != null){
            query += " OFFSET ? LIMIT ?";
            params.add(Presences.PAGE_SIZE * page);
            params.add(Presences.PAGE_SIZE);
        }
        
        query = ";"
```
ça t'évite un else.
Par la même occase, la pagination en SQL étant un sujet régulier, tu devrais être en mesure d'externaliser ça peut-être (dans un helper par exemple)

2023-05-26 13:04 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +    }
Ah je reconnais là un petit copier collé interdit 😋 
Si tu dupliques une fonction pour ne changer que le sélecteur, c'est que potentiellement y'a moyen de le mutualiser.
Je te laisses réfléchir à comment 😉

2023-05-26 13:04 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/controller/AlertController.java
> +                            pageCountPromise.future().result().getInteger(Field.COUNT, 0) / Presences.PAGE_SIZE;
La pagination étant une notion régulière des endpoints, peut-être que tu peux essayer de rendre ça générique ! (dans un helper par exemple).

2023-05-26 13:04 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/AlertService.java
> +    void getPageCount(String structureId, List<String> types, List<String> students, String startDate, String endDate, String startTime, String endTime, Handler<Either<String,JsonObject>> handler);
```suggestion
    Future<JsonObject> getPageCount(String structureId, List<String> types, List<String> students, String startDate, String endDate, String startTime, String endTime);
```

2023-05-26 13:04 UTC, qpic-cgi commented on presences/src/main/resources/public/ts/controllers/alerts.ts
> +        console.log(`Scroll${this.filter.page}`);
supprime

2023-05-26 14:01 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/AlertService.java
> +    void getPageCount(String structureId, List<String> types, List<String> students, String startDate, String endDate, String startTime, String endTime, Handler<Either<String,JsonObject>> handler);
Pas besoin de JsonObject. Si l'on veux juste le nombre de page, tu peux renvoyer un Integer directement.

2023-05-26 14:01 UTC, BastienBenard commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +    public Future<JsonArray> getAlertsStudents(String structureId, List<String> types, List<String> students, String startDate, String endDate, String startTime, String endTime, Integer page) {
A voir avoir @flmartineau mais ce serais cool de mettre ces fonctions en déprécié et de crée une fonction qui retourne un model Alert et qui prend en paramètre un model FilterAlert

2023-05-30 14:59 UTC, qpic-cgi requested changes

2023-05-30 14:59 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/controller/AlertController.java
> +                                    .map(o -> (JsonObject)o)
```suggestion
                            .filter(JsonObject.class::isInstance)
                            .map(JsonObject.class::cast)
```
(sinon y'en a qui seront pas content 😋)

2023-05-30 14:59 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/SQLHelper.java
> +            return " WHERE structure_id = ?";
Le truc, c'est que si la structure c'est le 2ème filtre que tu veux checker, cette méthode ne fonctionne pas

2023-05-30 14:59 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/SQLHelper.java
> +            return " AND type IN " + Sql.listPrepared(types);
Pareil ici, tu ne peux pas faire 
"WHERE type IN " ...
tu es contraint par le AND.

De plus, je ne sais pas si c'est très générique de checker un "type" comme ça.
Pour moi c'est plutôt un champ spécifique et donc pas intéressant dans un helper.

2023-05-31 13:33 UTC, qpic-cgi requested changes
Attentions aux indentation dans tes fichiers !

2023-05-31 13:33 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/SQLHelper.java
> +    }
Ces 2 premières méthodes sont overkills. tu peux supprimer ^^

2023-05-31 13:33 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +        boolean firstFilter = false;
arf non, ça t'oblige à répéter ce code: 
```
if (firstFilter) {
                query += SQLHelper.and();
            }
```
plusieurs fois, c'est pas super jolie.
Utilise quelque chose comme ça plutôt si tu veux : https://github.com/OPEN-ENT-NG/presences/blob/dev/presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java#L79

2023-06-01 07:51 UTC, qpic-cgi requested changes

2023-06-01 07:51 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/SQLHelper.java
> +    public static String maybeAnd(boolean firstFilter) {
supprime cette méthode

2023-06-01 14:38 UTC, flmartineau approved these changes

2023-06-01 14:38 UTC, flmartineau commented on presences/src/main/java/fr/openent/presences/controller/AlertController.java
> +        AlertFilterModel alertFilter = new AlertFilterModel(request.getParam(Field.ID), types, students, startDate, endDate, "00:00:00", "23:59:59", page);
Utilise plutôt DateHelper.DEFAULT_END_TIME et DateHelper.DEFAULT_START_TIME

2023-06-01 14:38 UTC, flmartineau commented on presences/src/main/resources/public/ts/services/AlertService.ts
> +            let pageFilter = page != null ? `page=${page}&` : '';
typage

2023-06-01 14:49 UTC, qpic-cgi requested changes

2023-06-01 14:49 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/PaginationHelper.java
> +    public static JsonObject getPaginationResponse(Integer page, Integer elementCount, List<Alert> data){
```suggestion
    public static JsonObject getPaginationResponse(Integer page, Integer elementCount, List<?> data){
```

2023-06-01 14:49 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/SQLHelper.java
> +    }
```suggestion
    public static String filterList(String field, List<Object> list, JsonArray params){
        if (!list.isEmpty()) {
            params.addAll(new JsonArray(list));
            return String.format(" %s IN %s", field, Sql.listPrepared(list));
        }
        return "";
    }
```
Quitte à être générique, soyons le jusqu'au bout !

dans ton appel ça ferait:
`SqlHelper.filterList('student_id', students, params)`

2023-06-01 14:49 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +        query += ";";
```suggestion
        query += SQLHelper.addLimitOffeset(Presences.ALERT_PAGE_SIZE, Presences.ALERT_PAGE_SIZE * alertFilter.getPage(), params) +";";
```

2023-06-01 15:18 UTC, qpic-cgi requested changes

2023-06-01 15:18 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/helper/SQLHelper.java
> +    }
pense à supprimer la fonction "students"

2023-06-01 15:18 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +        if (!alertFilter.getTypes().isEmpty()) {
SQLHelper.filterList("type", alertFilter.getTypes(), params) => utilise ton outil générique !

2023-06-01 15:25 UTC, qpic-cgi requested changes

2023-06-01 15:25 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +            conditions.append(SQLHelper.filterList("type", alertFilter.getTypes(), params));
donc ta requête ça va être "... AND type in (?, ?, ?) AND type in (?, ?, ?)" ?
tu es sûr de vouloir de vouloir checker 2 fois le type ?

2023-06-13 14:07 UTC, qpic-cgi approved these changes

2023-06-13 14:07 UTC, qpic-cgi commented on presences/src/main/java/fr/openent/presences/service/impl/DefaultAlertService.java
> +        query += SQLHelper.addLimitOffeset(Presences.ALERT_PAGE_SIZE, Presences.ALERT_PAGE_SIZE * alertFilter.getPage(), params) + ";";
offeset ? 😋

2023-06-13 14:28 UTC, merged