feat(regularisation) : #MA-470 add feedback on absence regularisation
OPEN-ENT-NG/presences pull request #326
Opened 2023-06-05 12:20 UTC by Alex-Delaveau

## Describe your changes
Add a confirmation toaster on absence regularisation.
![image](https://github.com/OPEN-ENT-NG/presences/assets/57497688/4cd1fe14-3b97-40f3-afbf-a13533dd6710)

## Checklist tests
Add an absence that is regularizable, then go to the dashboard side panel, regularize it, and check if you receive a confirmation feedback.
## Issue ticket number and link
[MA-470](https://jira.support-ent.fr/browse/MA-470)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-06-05 13:20 UTC, flmartineau approved these changes

2023-06-05 14:55 UTC, qpic-cgi requested changes

2023-06-05 14:55 UTC, qpic-cgi commented on presences/src/main/resources/public/ts/models/CounsellorAbsence.ts
>              notify.error('presences.absences.update_regularized.error');
tu vois, tu peux peut-être gérer ton feedback ici du coup
(étant donné qu'il est déjà géré dans le catch comme ça.

2023-06-05 14:55 UTC, qpic-cgi commented on presences/src/main/resources/public/ts/controllers/widgets/absences.ts
> +                toasts.confirm('presences.absences.update_regularized')
Je crois que désormais on utilise notify (et plus toast).
A voir avec ta PO.

2023-06-05 14:55 UTC, qpic-cgi commented on presences/src/main/resources/public/ts/models/Event/Event.ts
> +            return false;
pareil que les coms plus haut

2023-06-06 09:06 UTC, Alex-Delaveau commented on presences/src/main/resources/public/ts/controllers/widgets/absences.ts
> +                toasts.confirm('presences.absences.update_regularized')
J'ai vu avec Celia toast est mieux et c'est celui que ode veulent garder sur le long terme apparement.

2023-06-06 10:07 UTC, qpic-cgi requested changes

2023-06-06 10:07 UTC, qpic-cgi commented on presences/src/main/resources/public/ts/controllers/widgets/absences.ts
> +            let res;
type

2023-06-06 12:27 UTC, qpic-cgi approved these changes

2023-06-06 13:07 UTC, merged